name: "Build"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: compile-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🚀 Run release-please
        if: github.event_name != 'pull_request'
        uses: googleapis/release-please-action@v4
        id: release-please
        with:
          config-file: .github/release-please-config.json # ✅ Explicitly specify the config file
          manifest-file: .github/release-please-manifest.json
      
      - name: 🏗️ Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
            target: wasm32-unknown-unknown
            toolchain: stable
            components: rustfmt, clippy

      - name: Install wasm-pack
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libssl-dev
          cargo install wasm-pack
          cargo install candid-extractor

      - name: 🏗️ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.12.3"
      
      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.0.0'
          cache: 'pnpm'

      - name: 🏗️ Install dependencies
        run: pnpm install
    
      - name: 🏗️ Build
        run: pnpm build:release
        